### ISSUE TITLE
file isn't output on aborting

### ISSUE THREAD

**Issue by gosteev** [imagemin/jpeg-recompress-bin#15]
hello. i use `gulp-image` package, that has `jpeg-recompress-bin` inside it. 
i'm facing the next problem:
```
[16:48:48] Command failed: D:\b_media\node_modules\jpeg-recompress-bin\vendor\jpeg-recompress.exe --strip --min 95 C:\Users\gosteev\AppData\Local\Temp\d8188d00-21ba-42b7-a480-455718a8178f C:\Users\gosteev\AppData\Local\Temp\30f922a0-68ae-4fca-a0be-d953f6bf826a
ssim at q=95 (95 - 95): 0.999987
ssim at q=95 (95 - 94): 0.999987
ssim at q=95 (95 - 94): 0.999987
ssim at q=95 (95 - 94): 0.999987
ssim at q=95 (95 - 94): 0.999987
Final optimized ssim at q=95: 0.999975
New size is 113% of original (saved 0 kb)
Output file is larger than input, aborting!
```

when output file is larger, no file outputs. seems like [that](https://github.com/imagemin/imagemin-jpeg-recompress/issues/3) is something similar. 
how can i make non-optimized files to continue piping?
Thanks

**Comment by shinnn** [comment]
It should be handled by gulp-image. [*Example*](https://github.com/imagemin/imagemin-jpeg-recompress/blob/aa49931ee9508aadcac2eaf5de488fd6044ad0b2/index.js#L94)
